# establishes backend protocol and publication branch

backend:
  name: git-gateway
  repo: "TyrellHaywood/the-garden-spot"
  api_root: https://api.github.com
  branch: main
media_folder: "images/uploads"

collections:
  #-----o0oO-0o.0-00.-----HOMEPAGE-COLLECTIONS-Oo0OoO.-O0.o0Ooo--------
  - name: "spotlights"
    label: "Spotlights"
    folder: "_posts/spotlights"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "_posts/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "homepage"
    label: "Homepage"
    folder: "_posts/homepage"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "mainSpotlight"
    label: "MainSpotlight"
    folder: "_posts/mainSpotlight"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }

  #-----o0oO-0o.0-00.-----ABOUT-US-COLLECTIONS-Oo0OoO.-O0.o0Ooo--------

  - name: "imageOne"
    label: "ImageOne"
    folder: "_posts/imageOne"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "imageTwo"
    label: "ImageTwo"
    folder: "_posts/imageTwo"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "aboutUs"
    label: "AboutUs"
    folder: "_posts/aboutUs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "teamMember"
    label: "TeamMember"
    folder: "_posts/teamMember"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }

  #-----o0oO-0o.0-00.-----ABOUT-US-COLLECTIONS-Oo0OoO.-O0.o0Ooo--------

  - name: "volunteerImg"
    label: "VolunteerImg"
    folder: "_posts/volunteerImg"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "getInvolved"
    label: "GetInvolved"
    folder: "_posts/getInvolved"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }

  #-----o0oO-0o.0-00.-----BLOG-COLLECTIONS-Oo0OoO.-O0.o0Ooo--------

  - name: "blogPost"
    label: "BlogPost"
    folder: "_posts/blogPost"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Month",
          name: "month",
          widget: "select",
          options:
            [
              "January",
              "February",
              "March",
              "April",
              "May",
              "June",
              "July",
              "August",
              "September",
              "October",
              "November",
              "December",
            ],
        }
      - {
          label: "Day",
          name: "day",
          widget: "number",
          options:
            [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
            ],
        }
      - {
          label: "Year",
          name: "year",
          widget: "select",
          options: [2024, 2025, 2026, 2027, 2028],
        }
      - { label: "Body", name: "body", widget: "markdown" }
